### ISSUE TITLE
Missing description under title

### ISSUE THREAD

**Issue by lfarah** [recruit-mtl/Graphs#2]
<img width="333" alt="screen shot 2016-06-24 at 11 47 07 am" src="https://cloud.githubusercontent.com/assets/6511079/16341014/66265a14-3a01-11e6-824c-c5702efa75e8.png">

Should be something like:

> Light weight charts view generater for iOS. Written in Swift.

**Comment by kokoron** [comment]
@lfarah Thanks!

**Comment by lfarah** [comment]
You're welcome! 😄
